server:
  port: 8001

#spring配置
spring:
  profiles:
    active: dev
  application:
    name: springboot-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_manage_sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.tafleo.hotel.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml